# Site wide configuration

title: "1412"
description: "生活就像海洋，只有意志坚强的人才能到达彼岸。"
logo: 小兔子穿花衣.jpg
teaser: # 400x250 px default teaser image used in image archive grid
locale: zh_TW # 本地化翻譯
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: hanteng
  email: hantengliao@qq.com
  twitter: hanteng
  google:
    ad-client:
    ad-slot:
  bio: "赖懂伊，网页设计与制作初级玩家。"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
